### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by Slappy826**
I've gone ahead and cleaned up a lot of the code for you, should look a lot nicer now!

🎉🎉🥳🥳

### CODE REVIEW

**Comment by rbx-nsg** [comment]
Funny

**Comment by BrentDaMage** [comment]
lol

**Comment by XlXi** [comment]
lmao

**Comment by Yakov5776** [comment]
@rbx-nsg I've checked it, it's ready to be merged

**Comment by ohoshk** [comment]
So awesome

**Comment by Slappy826** [comment]
Could you potentially reconsider my PR request?

**Comment by rbx-nsg** [comment]
No, but I might IP ban you from this repo

**Comment by Yakov5776** [comment]
nahh hwid ban is better

**Comment by dev-natalie** [comment]
this is so dope

**Pull request closed without merging**
